In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Data Exploration 

In [2]:
df = pd.read_excel("C://Users//navs9//Downloads//Employee.xlsx")
df

Company   Age  Salary     Place Country  Gender
0        TCS  20.0     NaN   Chennai   India       0
1    Infosys  30.0     NaN    Mumbai   India       0
2        TCS  35.0  2300.0  Calcutta   India       0
3    Infosys  40.0  3000.0     Delhi   India       0
4        TCS  23.0  4000.0    Mumbai   India       0
..       ...   ...     ...       ...     ...     ...
143      TCS  33.0  9024.0  Calcutta   India       1
144  Infosys  22.0  8787.0  Calcutta   India       1
145  Infosys  44.0  4034.0     Delhi   India       1
146      TCS  33.0  5034.0    Mumbai   India       1
147  Infosys  22.0  8202.0    Cochin   India       0

[148 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Company  140 non-null    object 
 1   Age      130 non-null    float64
 2   Salary   124 non-null    float64
 3   Place    134 non-null    object 
 4   Country  148 non-null    object 
 5   Gender   148 non-null    int64  
dtypes: float64(2), int64(1), object(3)
memory usage: 7.1+ KB


In [4]:
df.dtypes

Company     object
Age        float64
Salary     float64
Place       object
Country     object
Gender       int64
dtype: object

In [5]:
df.describe()

Age       Salary      Gender
count  130.000000   124.000000  148.000000
mean    30.484615  5312.467742    0.222973
std     11.096640  2573.764683    0.417654
min      0.000000  1089.000000    0.000000
25%     22.000000  3030.000000    0.000000
50%     32.500000  5000.000000    0.000000
75%     37.750000  8000.000000    0.000000
max     54.000000  9876.000000    1.000000

In [6]:
df.Age.median()

32.5

In [7]:
df.Salary.median()

5000.0

In [8]:
df.Gender.median()

0.0

In [9]:
# Renaming columns
df.rename(columns={'Company': 'Company name', 'Age': 'Age of employee', 'Salary':'Salary of employee','Place':'Place of employee','Country':'Country of employee','Gender':'Gender of employee'}, inplace=True)

In [10]:
df

Company name  Age of employee  Salary of employee Place of employee   
0            TCS             20.0                 NaN           Chennai  \
1        Infosys             30.0                 NaN            Mumbai   
2            TCS             35.0              2300.0          Calcutta   
3        Infosys             40.0              3000.0             Delhi   
4            TCS             23.0              4000.0            Mumbai   
..           ...              ...                 ...               ...   
143          TCS             33.0              9024.0          Calcutta   
144      Infosys             22.0              8787.0          Calcutta   
145      Infosys             44.0              4034.0             Delhi   
146          TCS             33.0              5034.0            Mumbai   
147      Infosys             22.0              8202.0            Cochin   

    Country of employee  Gender of employee  
0                 India                   0  
1                 India                   0  
2                 India                   0  
3                 India                   0  
4                 India                   0  
..                  ...                 ...  
143               India                   1  
144               India                   1  
145               India                   1  
146               India                   1  
147               India                   0  

[148 rows x 6 columns]

In [12]:
#unique values in each column
n=df.nunique()
n

Company name            6
Age of employee        29
Salary of employee     40
Place of employee      11
Country of employee     1
Gender of employee      2
dtype: int64

In [ ]:
#finding length of unique values in each column

In [14]:
df['Company name'].unique()

array(['TCS', 'Infosys', 'CTS', nan, 'Tata Consultancy Services',
       'Congnizant', 'Infosys Pvt Lmt'], dtype=object)

In [15]:
df['Age of employee'].unique()

array([20., 30., 35., 40., 23., nan, 34., 45., 18., 22., 32., 37., 50.,
       21., 46., 36., 26., 41., 24., 25., 43., 19., 38., 51., 31., 44.,
       33., 17.,  0., 54.])

In [16]:
df['Salary of employee'].unique()

array([  nan, 2300., 3000., 4000., 5000., 6000., 7000., 8000., 9000.,
       1089., 1234., 3030., 3045., 3184., 4824., 5835., 7084., 8943.,
       8345., 9284., 9876., 2034., 7654., 2934., 4034., 5034., 8202.,
       9024., 4345., 6544., 6543., 3234., 4324., 5435., 5555., 8787.,
       3454., 5654., 5009., 5098., 3033.])

In [18]:
df['Place of employee'].unique()

array(['Chennai', 'Mumbai', 'Calcutta', 'Delhi', 'Podicherry', 'Cochin',
       nan, 'Noida', 'Hyderabad', 'Bhopal', 'Nagpur', 'Pune'],
      dtype=object)

In [20]:
#correcting the spelling
df['Place of employee'].replace('Podicherry','Pondicherry',inplace=True)
df['Place of employee'].unique()

array(['Chennai', 'Mumbai', 'Calcutta', 'Delhi', 'Pondicherry', 'Cochin',
       nan, 'Noida', 'Hyderabad', 'Bhopal', 'Nagpur', 'Pune'],
      dtype=object)

In [21]:
df['Country of employee'].unique()

array(['India'], dtype=object)

In [22]:
df['Gender of employee'].unique()

array([0, 1], dtype=int64)

### Data Cleaning